const CarritoTypes = {
  SHOW_CART:'SHOW_CART',
  ADD_PRODUCT: "ADD_PRODUCT",
  DECREASE_PRODUCT: "DECREASE_PRODUCT",
  SET_SUBTOTAL: "SET_SUBTOTAL",
  GET_DISCOUNTS: "GET_DISCOUNTS",
  GET_ALL_DISCOUNTS:"GET_ALL_DISCOUNTS",
  ERROR_GET_DISCOUNTS:"ERROR_GET_DISCOUNTS",
}

export default CarritoTypes;