const GaleryTypes = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  ERROR_GET_PRODUCTS:"ERROR_GET_PRODUCTS",
  GET_ALL_DISCOUNTS: "GET_ALL_DISCOUNTS",
  ERROR_GET_DISCOUNTS:"ERROR_GET_DISCOUNTS",
  SEARCH_PRODUCT:'SEARCH_PRODUCT',
}

export default GaleryTypes;